### ISSUE TITLE
function returning default breadcrumb markup

### ISSUE THREAD

**Issue by piotrpog** [youandmedigital/craft-breadcrumb#9]
Having to define breadcrumb markup manually each time i use plugin is s bit if a chore. There should be function that returns ready to use breadcrumb HTML, ready to use, implemenying all nessesary schema tags.

Do you accept pull requests? If yes, i can do this for you.

**Comment by jonleverrier** [comment]
Hi @piotrpog 

Thanks for taking time to report this issue and offer a pull request.

I like your ideas but it makes the plugin opinionated. 

What happens if somebody wants to display a visual breadcrumb using BEM syntax or using Tailwind classes as an example? The same could be said about the HTML markup.

I appreciate BreadcrumbList schema is more defined, but again, what happens if somebody wants to markup a [multiple breadcrumb trail](https://developers.google.com/search/docs/data-types/breadcrumb#html_example)?

I think these decisions are best left for the developer to decide via Twig, not the plugin. 

Once you create a Twig component, it can be easily copied across projects.

**Comment by piotrpog** [comment]
@jonleverrier 
Well, classes can be passed to components using function parameters. Not only classes but whole arrays that are later transformed into HTML attributes like in Craft attr() function.

I feel that having such additional function won't hurt - for "lazy" people it would be ready to use, for devs that need something custom, there would be still a possibility of manual rendering.

Just like for example in verbb navigation plugin or freeform - it can produce ready to use markup - or you can render something manually using variables.

But I respect your decision :)

**Comment by jonleverrier** [comment]
Thanks @piotrpog - I appreciate your feedback :)
